spring:
  #配置数据源
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.10.68:5432/dna_portal
    username: dna_portal
    password: dna_portal
    driverClassName: org.postgresql.Driver

  jackson:
    # 对返回时间字段进行格式化
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  # redis 相关配置
  redis:
    host: 192.168.10.22
    port: 6381
    password: highershine

  # 文件上传大小配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

# session 超时时间hours
manage:
  session:
    timeout: 8

#MinIO配置
minio:
  endPoint: http://192.168.10.50:9000
  bucketName: web-portal
  accessKey: miniotest
  secretKey: miniotest
  connTimeOut: 10000
  maxConnections: 10
  maxErrorRetry: 50
  socketTimeOut: 10000