spring:
  #配置数据源
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.10.68:5432/dna_portal
    username: dna_website
    password: dna_website
    driverClassName: org.postgresql.Driver

  jackson:
    # 对返回时间字段进行格式化
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  # redis 相关配置
  redis:
    password: highershine
    cluster:
      max-redirects: 10
      nodes: 192.168.50.140:8001,192.168.50.140:8004,192.168.50.141:8002,192.168.50.141:8005,192.168.50.142:8003,192.168.50.142:8006

  # 文件上传大小配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

#MinIO配置
minio:
  endPoint: http://192.168.10.22:9000
  bucketName: web-portal
  accessKey: miniotest
  secretKey: miniotest
  connTimeOut: 10000
  maxConnections: 10
  maxErrorRetry: 50
  socketTimeOut: 10000

# person_query接口调用配置
person:
  query:
    addr: http://192.168.10.58/person_query/personQuery
    salt: 1qaz2wsx3edc4rfv5tgb6yhn7ujm8ik,9ol.0p;/
    systemkey: 3e977d01-7f7b-4d59-ad7c-36e6e46a929d

oauth2:
  server:
    # oauth_client_details配置的clientId
    clientId: website
    # oauth_client_details配置的client_secret(明文)
    clientSecret: 2020
    # oauth2-server服务的地址
    tokenAddr: http://ip:port/oauth2-server/oauth/token
    checkTokenAddr: http://ip:port/oauth2-server/oauth/check_token
    # jwt密钥
    jwtSecret: highershine-jwt-key
