spring:
  #配置数据源
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.10.68:5432/dna_portal
    username: dna_website
    password: dna_website
    driverClassName: org.postgresql.Driver

  # redis 相关配置
  redis:
    password: highershine
    cluster:
      max-redirects: 10
      nodes: 192.168.50.140:8001,192.168.50.140:8004,192.168.50.141:8002,192.168.50.141:8005,192.168.50.142:8003,192.168.50.142:8006

oauth2:
  server:
    # jwt密钥
    jwtSecret: highershine-jwt-key